@BookStore.Api_HostAddress = http://localhost:5000

POST {{BookStore.Api_HostAddress}}/api/authors
Content-Type: application/json

  {
    "name": "string",
    "email": "userexample.com",
    "description": "string"
  }


###
